#!/bin/bash
# scripts/update-version.sh — Canonical version stamper
# Per ~/.claude/BUILD_CONVENTIONS.md § Versioning:
#   MAJOR  = manual milestone (edit the assignment below)
#   MINOR  = auto-bumped per build (codebase-change-unit counter)
#   BUILD  = epoch_minutes % 100000 (artifact disambiguation)
#
# Writes version.txt (canonical) and every package.json in the workspace
# so all packages stamp identical version strings.
#
# Usage:
#   bash scripts/update-version.sh              # Normal: bump MINOR, new BUILD
#   bash scripts/update-version.sh --rebuild    # Re-stamp BUILD only, keep MAJOR.MINOR
#   bash scripts/update-version.sh --lock       # Write release.lock from current version.txt
#
# Cross-platform parity (Linux now, Windows later):
#   1. Build first platform:  bash scripts/update-version.sh
#   2. Freeze for remaining:  bash scripts/update-version.sh --lock
#   3. Build other platforms: bash scripts/update-version.sh  (reads release.lock)
#   4. After all platforms:   rm release.lock
#
# If only the build infrastructure changed (this script, CI YAML, etc.),
# use --rebuild to recalculate BUILD without bumping MINOR.

set -e
cd "$(dirname "$0")/.."
PROJECT_ROOT="$(pwd)"

LOCK_FILE="$PROJECT_ROOT/release.lock"
REBUILD_MODE=false
LOCK_MODE=false

for arg in "$@"; do
  case "$arg" in
    --rebuild) REBUILD_MODE=true ;;
    --lock)    LOCK_MODE=true ;;
    *) echo "[update-version] Unknown flag: $arg" >&2; exit 1 ;;
  esac
done

# ── --lock: write release.lock from current version.txt, then exit ──────────
if [ "$LOCK_MODE" = true ]; then
  CURRENT_VERSION=$(tr -d '[:space:]' < version.txt)
  MAJOR=$(echo "$CURRENT_VERSION" | cut -d. -f1)
  MINOR=$(echo "$CURRENT_VERSION" | cut -d. -f2)
  BUILD_NUM=$(echo "$CURRENT_VERSION" | cut -d. -f3)
  cat > "$LOCK_FILE" << EOF
# release.lock — frozen version for coordinated multi-platform builds.
# Generated by: bash scripts/update-version.sh --lock
# Delete this file after all platform builds are complete.
MAJOR=${MAJOR}
MINOR=${MINOR}
BUILD_NUM=${BUILD_NUM}
EOF
  echo "[update-version] Wrote release.lock: ${MAJOR}.${MINOR}.${BUILD_NUM}"
  echo "  Subsequent runs will use these frozen values until release.lock is removed."
  exit 0
fi

# ── Coordinated release lock (freezes values for multi-platform) ────────────
if [ -f "$LOCK_FILE" ] && [ "$REBUILD_MODE" = false ]; then
  echo "[update-version] Using frozen release.lock values"
  # shellcheck source=/dev/null
  source "$LOCK_FILE"   # MAJOR, MINOR, BUILD_NUM pre-set
  DISPLAY_VERSION="${MAJOR}.${MINOR}.${BUILD_NUM}"
else
  # ── Manual MAJOR — edit for milestone releases ────────────────────────────
  MAJOR=0

  # ── Read current MAJOR.MINOR from canonical source (version.txt) ──────────
  CURRENT_VERSION=$(tr -d '[:space:]' < version.txt 2>/dev/null || echo "0.10.0")

  CURRENT_MAJOR=$(echo "$CURRENT_VERSION" | cut -d. -f1)
  CURRENT_MINOR=$(echo "$CURRENT_VERSION" | cut -d. -f2)

  if [ "$REBUILD_MODE" = true ]; then
    # ── --rebuild: keep MAJOR.MINOR, recalculate BUILD only ──────────────────
    # Use this when only build infrastructure changed (this script, CI YAML,
    # Dockerfile, etc.) — not a real codebase change, so MINOR stays.
    MINOR="$CURRENT_MINOR"
    BUILD_NUM=$(printf "%05d" $(($(date +%s) / 60 % 100000)))
    DISPLAY_VERSION="${MAJOR}.${MINOR}.${BUILD_NUM}"
    echo "[update-version] Re-stamp (build-only): ${DISPLAY_VERSION}  (MAJOR.MINOR unchanged at ${MAJOR}.${MINOR})"
  else
    # ── Auto-bump MINOR (or reset to 0 if MAJOR was bumped) ─────────────────
    if [ "$CURRENT_MAJOR" = "$MAJOR" ]; then
      MINOR=$((CURRENT_MINOR + 1))
    else
      MINOR=0
    fi

    # ── 5-digit epoch BUILD (printf %05d pads only when natural <5 digits) ──
    # Values >=10000 stay at natural width (e.g. 98278 → 98278 unchanged).
    # Values <10000 get leading zeros so lexicographic filename sort matches
    # chronological sort (e.g. 228 → 00228).
    BUILD_NUM=$(printf "%05d" $(($(date +%s) / 60 % 100000)))

    DISPLAY_VERSION="${MAJOR}.${MINOR}.${BUILD_NUM}"
    echo "[update-version] Stamping version: ${DISPLAY_VERSION}  (was ${CURRENT_MAJOR}.${CURRENT_MINOR}; MINOR ${CURRENT_MINOR}→${MINOR})"
  fi
fi

# ── Write canonical version.txt ────────────────────────────────────────────
echo "${DISPLAY_VERSION}" > version.txt

# ── Write root package.json ────────────────────────────────────────────────
sed -i 's/"version": "[^"]*"/"version": "'"${DISPLAY_VERSION}"'"/' package.json

# ── Write all workspace package.json files that share the repo version ─────
# (skips packages with intentionally divergent versions like tools/serve@0.6.0)
for pkg in packages/*/package.json apps/*/package.json tools/*/package.json; do
  [ -f "$pkg" ] || continue
  CURRENT_PKG_VERSION=$(node -p "require('./$pkg').version" 2>/dev/null || continue)
  # Only update packages whose MAJOR.MINOR matches the stamped MAJOR.MINOR.
  # This preserves intentionally divergent versions (e.g. tools/serve@0.6.0).
  PKG_MAJOR=$(echo "$CURRENT_PKG_VERSION" | cut -d. -f1)
  PKG_MINOR=$(echo "$CURRENT_PKG_VERSION" | cut -d. -f2)
  if [ "$PKG_MAJOR" = "$MAJOR" ] && [ "$PKG_MINOR" = "$MINOR" ]; then
    sed -i 's/"version": "[^"]*"/"version": "'"${DISPLAY_VERSION}"'"/' "$pkg"
  fi
done

# ── Export for downstream build scripts / CI ───────────────────────────────
export PROJECT_VERSION="${DISPLAY_VERSION}"
export PROJECT_VERSION_BASE="${MAJOR}.${MINOR}"
export PROJECT_BUILD_NUM="${BUILD_NUM}"

echo ""
echo "Stamped:"
echo "  version.txt:        ${DISPLAY_VERSION}"
echo "  root package.json:  ${DISPLAY_VERSION}"
echo "  workspace packages: all matching ${MAJOR}.${MINOR}.* → ${DISPLAY_VERSION}"
